preset: psr2

risky: true

linting: true

finder:
    path:
        - "examples"
        - "src"
        - "tests"

enabled:
    - binary_operator_spaces
    - ordered_imports
    - short_array_syntax
